### ISSUE TITLE
BadDicom process killed when generating a large amount of studies

### ISSUE THREAD

**Issue by heiwiper** [HicServices/BadMedicine.Dicom#91] opened 2022-05-17 13:11 UTC
**Describe the bug**
BadDicom process was killed while generating a large amount of studies.

**To Reproduce**
It might be easier to reproduce using a VM with a 2 GB of RAM
1. generate many studies.
```shell
./BadDicom ./dicoms/ 2000 3000
```
3. Wait until process is killed.

**Expected behavior**
Generate 3000 studies for 2000 patients.

**Screenshots**
![image](https://user-images.githubusercontent.com/12894695/168801850-f0f82dbe-f682-4ad1-a52a-21b34fd149f3.png)

**Desktop (please complete the following information):**
 - OS: Debian Bullseye
 - Browser Firefox 100.0 (I don't get why is this mentioned in the report)
 - Version 0.0.11
 - RAM 16 GB (I thought this might be useful)

**Additional context**
I was trying to generate around 3000 study for 2000 patients which I estimated it would consume less than 500 GB of storage, the `BadDicom` process was killed by the kernel after a few minutes and the generated studies were around 17 GB.
I investigated the issue and found out that the process was killed by the kernel due to memory exhaustion as mentioned [here](https://stackoverflow.com/questions/726690/what-killed-my-process-and-why)
When I checked the logs mention in one of the responses of that StackOverflow's question (/var/log/kern.log) I found the following after looking up `BadDicom`
```
Out of memory: Killed process 274282 (BadDicom) total-vm:26910428kB, anon-rss:9519364kB, file-rss:12kB, shmem-rss:0kB, UID:1000 pgtables:46804kB oom_score_adj:0
```
After trying for a second time, I started the system monitor and I noticed high usage of memory by the process `BadDicom` which kept increasing until the system froze for a minute and then it went back to normal but the process was killed.
So I would guess there's a memory leak in this application which is causing this issue.

**Comment by tznind** [comment] 2022-05-17 14:39
@jas88 just tagging you on this.  Any ideas?

**Comment by heiwiper** [comment] 2022-05-17 15:37
Let me know if there's anything I can help with.
Also thanks for mentioning the `--NoPixels` option I did read the options the other day but totally forgot about it when I had to use it today. For the moment I'm using the command inside a shell script loop as a workaround.

**Comment by jas88** [comment] 2022-05-17 23:05
Progress:
- Confirmed the issue is a known memory leak in the legacy libgdiplus shim used to run otherwise Windows-only GDI code on Linux - already tagged to fix in #81 for other reasons
- Part-implemented replacement code in #94 (WIP)

**Comment by jas88** [comment] 2022-05-18 10:30
This should be resolved once #94 is merged in, removing the reliance on libgdiplus.
Pixel output is a bit garbled for me in both versions, so I've opened a fresh issue #95 to track that.

**Closed** 2022-05-18 10:55 UTC

**Comment by tznind** [comment] 2022-05-18 12:02
Can confirm that the PR has made the memory issue go away on my laptop.  I will push a release of BadMedicine.Dicom now

**Comment by tznind** [comment] 2022-05-18 12:20
@heiwiper please can you test https://github.com/HicServices/BadMedicine.Dicom/releases/tag/v0.0.12 and confirm that the memory issue has also been resolved for you.

**Comment by heiwiper** [comment] 2022-05-22 11:22
I just had the chance to test this today.
I'm using the binaries from the last version (0.0.12), I generated 3300 studies including pixel data an can confirm the issue has been resolved.
Thank you so much for the quick fix 🚀 !
